name: Add artifact links to pull request

on:
  workflow_run:
    workflows: ["Build IITC Button"]
    types: [completed]
  workflow_dispatch:

jobs:
  comment-links:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact list from API
        id: get-artifacts
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runId = ${{ github.event.workflow_run.id }};
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId
            });
            const headers = "| Artifact Name | Download Link |\\n| ------------- | ------------- |\\n";
            const table = artifacts.data.artifacts.reduce((acc, artifact) => {
              const downloadURL = `https://github.com/${context.repo.owner}/${context.repo.repo}/suites/${runId}/artifacts/${artifact.id}`;
              acc.push(`| ${artifact.name} | [Download](${downloadURL}) |`);
              return acc;
            }, []).join('\\n');
            return headers + table;

      - name: Add comment with artifact links to PR
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ steps.get-artifacts.outputs.result != '' }}
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          body: >
            Build completed successfully. Below are the download links for the build artifacts in a table format:

            ${{ steps.get-artifacts.outputs.result }}

            Artifacts will only be retained for 90 days.
