name: Add artifact links to pull request

on:
  workflow_run:
    workflows: ["Build IITC Button"]
    types: [completed]
  workflow_dispatch:

jobs:
  comment-links:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact list from API
        id: get-artifacts
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runId = ${{ github.event.workflow_run.id }};
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId
            });
            let table = "| Artifact Name | Download Link |\n| ------------- | ------------- |\n";
            for (const artifact of artifacts.data.artifacts) {
              const downloadURL = `https://github.com/${context.repo.owner}/${context.repo.repo}/suites/${runId}/artifacts/${artifact.id}`;
              table += `| ${artifact.name} | [Download](${downloadURL}) |\n`;
            }
            const message = "Build completed successfully. Below are the download links for the build artifacts:\n"+table+"\nArtifacts will only be retained for 90 days.";
            console.log(message);
            return message;

      - name: Comment with artifact links for PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr_artifacts
          number: ${{ github.event.workflow_run.pull_requests[0].number }}
          message: ${{ steps.get-artifacts.outputs.result }}
