name: Add artifact links to pull request
on:
  workflow_run:
    workflows: ['Build IITC Button']
    types: [completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  artifacts-url-comments:
    name: add artifact links to pull request and related issues job
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Get artifact url'
        uses: actions/github-script@v6
        with:
         script: |
           let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
           });
           let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
             return artifact.name == "build"
           })[0];
           console.log(matchArtifact);
           core.exportVariable('ARTIFACT_URL', matchArtifact.url);

      - name: Comment with build url for PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr_release
          number: ${{ env.PR_NUMBER }}
          message: |
            ## 🤖 Pull request artifacts
            | file | commit |
            | ---- | ------ |
            | [`build.zip`](${{ env.ARTIFACT_URL }}) | commit |
